### ISSUE TITLE
Update spec to reflect addition of maplike<> to WebIDL

### ISSUE THREAD

**Issue by qdot** [WebAudio/web-midi-api#115] opened 2015-02-09 19:12 UTC
The blink implementation of WebMIDI is now using maplike<> (https://code.google.com/p/chromium/issues/detail?id=432683), and the firefox implementation (https://bugzilla.mozilla.org/show_bug.cgi?id=836897) will most likely use maplike<> once is in place (https://bugzilla.mozilla.org/show_bug.cgi?id=1123516). The spec should reflect this so we don't have discrepancies.

**Comment by yutakahirano** [comment] 2015-02-21 07:00
The problem is that ReSpec doesn't support maplike right now. https://github.com/w3c/respec/issues/361

**Comment by yutakahirano** [comment] 2015-02-23 07:48
I'm trying to fix that.

**Comment by toyoshim** [comment] 2015-03-06 06:37
shall we close this now, or keep it opened until ReSpec support maplike?

**Comment by yutakahirano** [comment] 2015-03-06 06:59
ReSpec released a new version containing maplike (it was faster than I expected) and I would like to drop the workaround soon.

**Comment by toyoshim** [comment] 2015-03-06 07:01
great!

**Comment by cwilso** [comment] 2015-03-06 20:58
Yutaka-san, reference?  I can't find a new release of ReSpec that supports maplike.

**Comment by yutakahirano** [comment] 2015-03-07 01:29
https://github.com/w3c/respec/pull/408

**Comment by cwilso** [comment] 2015-03-09 16:06
Done.

**Closed as completed by cwilso** 2015-03-09 16:06 UTC
